version: '3'

services:
  vanilla-frontend:
    build:
      context: .
    container_name: vanilla-frontend
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis:6379
  vanilla-frontend-cacher:
    build:
      context: .
    container_name: vanilla-frontend-cacher
    environment:
      - REDIS_URL=redis:6379
      - REDIS_INSECURE=true
    command: yarn build
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
  hardhat:
    build:
      context: ./contracts
    container_name: hardhat
    ports:
      - 8545:8545
